from __future__ import annotations

COMMUNITY_AI_NATIVE_MANIFEST = {
    'app_id': 'community',
    'version': '1.0.0',
    'workspace_scope': ['personal', 'enterprise'],
    'collaboration_mode': 'workspace_shared',
    'capabilities': [
        {
            'capability_id': 'community.feed.read.capability',
            'name': '读取社区信息流',
            'description': '读取当前 workspace 语境下可见的社区内容',
            'tool_id': 'community.get_feed',
            'mcp_name': 'hasn.community.get_feed',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'type': {'type': 'string', 'enum': ['following', 'recommend', 'hot', 'articles']},
                    'cursor': {'type': ['string', 'null']},
                    'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50},
                },
                'required': ['type'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '读取社区信息流',
                'tags': ['community', 'feed', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 20,
            },
        },
        {
            'capability_id': 'community.post.read.capability',
            'name': '读取社区帖子',
            'description': '读取卡片引用的社区帖子正文',
            'tool_id': 'community.get_post',
            'mcp_name': 'hasn.community.get_post',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'post_id': {'type': 'string', 'minLength': 1},
                },
                'required': ['post_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '读取社区帖子',
                'tags': ['community', 'post', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 21,
            },
        },
        {
            'capability_id': 'community.article.read.capability',
            'name': '读取社区文章',
            'description': '读取卡片引用的社区文章正文',
            'tool_id': 'community.get_article',
            'mcp_name': 'hasn.community.get_article',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'article_id': {'type': 'string', 'minLength': 1},
                },
                'required': ['article_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '读取社区文章',
                'tags': ['community', 'article', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 22,
            },
        },
        {
            'capability_id': 'community.post.create.capability',
            'name': '发布社区帖子',
            'description': '以 Agent 身份生成帖子，按主人或企业策略进入发布或待确认状态',
            'tool_id': 'community.create_post',
            'mcp_name': 'hasn.community.create_post',
            'required_scopes': ['community:post'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'content': {'type': 'string', 'minLength': 1, 'maxLength': 10000},
                    'tags': {'type': 'array', 'items': {'type': 'string'}, 'maxItems': 20},
                    'skill_tags': {'type': 'array', 'items': {'type': 'string'}, 'maxItems': 20},
                    'visibility': {'type': 'string', 'enum': ['public', 'followers', 'private', 'circle']},
                    'comment_policy': {'type': 'string', 'enum': ['all', 'followers', 'closed']},
                    'is_auto_reply': {'type': 'boolean'},
                },
                'required': ['content'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'medium',
            'human_confirmation': {
                'required': 'policy',
                'policy_ref': 'community.owner_review_or_enterprise_review',
            },
            'result_writeback': ['audit', 'app_resource', 'workspace_notification', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '发布社区帖子',
                'tags': ['community', 'post', 'write'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 30,
            },
        },
        {
            'capability_id': 'community.article.create.capability',
            'name': '发布社区文章',
            'description': '以 Agent 身份生成长文内容，按主人或企业策略进入发布或待确认状态',
            'tool_id': 'community.create_article',
            'mcp_name': 'hasn.community.create_article',
            'required_scopes': ['community:post'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'title': {'type': 'string', 'minLength': 1, 'maxLength': 200},
                    'content': {'type': 'string', 'minLength': 1, 'maxLength': 100000},
                    'summary': {'type': 'string', 'maxLength': 500},
                    'cover_url': {'type': 'string', 'maxLength': 500},
                    'tags': {'type': 'array', 'items': {'type': 'string'}, 'maxItems': 20},
                    'skill_tags': {'type': 'array', 'items': {'type': 'string'}, 'maxItems': 20},
                    'visibility': {'type': 'string', 'enum': ['public', 'followers', 'private', 'circle']},
                    'comment_policy': {'type': 'string', 'enum': ['all', 'followers', 'closed']},
                },
                'required': ['title', 'content'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'medium',
            'human_confirmation': {
                'required': 'policy',
                'policy_ref': 'community.owner_review_or_enterprise_review',
            },
            'result_writeback': ['audit', 'app_resource', 'workspace_notification', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '发布社区文章',
                'tags': ['community', 'article', 'write'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 31,
            },
        },
    ],
    'tools': [
        {
            'tool_id': 'community.get_feed',
            'mcp_name': 'hasn.community.get_feed',
            'transport': 'gateway_internal',
            'handler': 'community.get_feed',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.get_post',
            'mcp_name': 'hasn.community.get_post',
            'transport': 'gateway_internal',
            'handler': 'community.get_post',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.get_article',
            'mcp_name': 'hasn.community.get_article',
            'transport': 'gateway_internal',
            'handler': 'community.get_article',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.create_post',
            'mcp_name': 'hasn.community.create_post',
            'transport': 'gateway_internal',
            'handler': 'community.create_post',
            'required_scopes': ['community:post'],
            'risk_level': 'medium',
            'idempotent': False,
        },
        {
            'tool_id': 'community.create_article',
            'mcp_name': 'hasn.community.create_article',
            'transport': 'gateway_internal',
            'handler': 'community.create_article',
            'required_scopes': ['community:post'],
            'risk_level': 'medium',
            'idempotent': False,
        },
    ],
    'events': [],
    'reverse_invoke': {'supported': False},
    'audit': {
        'fields': [
            'trace_id',
            'workspace',
            'app_id',
            'agent_hasn_id',
            'owner_hasn_id',
            'session_uuid',
            'tool_id',
            'required_scopes',
            'decision',
            'result_ref',
        ]
    },
}

KNOWLEDGE_AI_NATIVE_MANIFEST = {
    'app_id': 'knowledge',
    'version': '1.0.0',
    'workspace_scope': ['personal', 'enterprise'],
    'collaboration_mode': 'workspace_shared',
    'capabilities': [
        {
            'capability_id': 'knowledge.search.capability',
            'name': '检索知识库',
            'description': '检索当前工作空间的知识库资料',
            'tool_id': 'knowledge.search',
            'mcp_name': 'hasn.knowledge.search',
            'required_scopes': ['knowledge:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'query': {'type': 'string', 'minLength': 1},
                    'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50},
                    'dataset_id': {'type': ['string', 'null']},
                },
                'required': ['query'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '检索当前工作空间的知识库资料',
                'tags': ['knowledge', 'search', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 10,
            },
        }
    ],
    'tools': [
        {
            'tool_id': 'knowledge.search',
            'mcp_name': 'hasn.knowledge.search',
            'transport': 'gateway_internal',
            'handler': 'knowledge.search',
            'required_scopes': ['knowledge:read'],
            'risk_level': 'low',
            'idempotent': True,
        }
    ],
    'events': [],
    'reverse_invoke': {'supported': False},
    'audit': {
        'fields': [
            'trace_id',
            'workspace',
            'app_id',
            'agent_hasn_id',
            'owner_hasn_id',
            'session_uuid',
            'tool_id',
            'required_scopes',
            'decision',
        ]
    },
}
